# Generated by Django 3.2.8 on 2021-11-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BistroMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuid', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(default='', max_length=2)),
                ('title', models.CharField(default='', max_length=20)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(default='', max_length=200)),
                ('image', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['menuid'],
            },
        ),
    ]
